[package]
name = "fn-dos7-cn"
version = "0.1.0"
description = "Turn a webpage into a desktop app"
authors = ["you"]
edition = "2021"

# 移动端（Android/iOS）要求提供 library target，桌面端则由 main.rs 调用这个 lib
[lib]
name = "pakeplus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# 目标：产物尽量小（这是同类工具的核心卖点之一）
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
